
BugGrabberDB = {
["lastSanitation"] = 3,
["session"] = 1755,
["errors"] = {
{
["message"] = "Interface/AddOns/RXPGuides/Targeting.lua:558: attempt to index field 'text' (a nil value)",
["time"] = 1782839301,
["locals"] = "self = StaticPopup1 {\n TopSpacer = FontString {\n }\n visibleButtons = <table> {\n }\n CoverFrame = Frame {\n }\n previousRegionKey = \"ButtonContainer\"\n ProgressBarSpacer = Texture {\n }\n DarkOverlay = Frame {\n }\n timeleft = 0\n ButtonContainer = Frame {\n }\n dialogInfo = <table> {\n }\n which = \"DECURSIVE_NOTICE_FRAME\"\n hideOnEscape = false\n ItemFrame = Frame {\n }\n MoneyInputFrame = StaticPopup1MoneyInputFrame {\n }\n AlertIcon = Texture {\n }\n ProgressBarFill = Texture {\n }\n ExtraButton = StaticPopup1ExtraButton {\n }\n Buttons = <table> {\n }\n BG = Frame {\n }\n EditBox = StaticPopup1EditBox {\n }\n ProgressBarBorder = Texture {\n }\n Dropdown = Button {\n }\n SubText = FontString {\n }\n heightPadding = 16\n Spinner = Frame {\n }\n numButtons = 1\n MoneyFrame = StaticPopup1MoneyFrame {\n }\n Text = StaticPopup1Text {\n }\n CloseButton = StaticPopup1CloseButton {\n }\n Separator = Texture {\n }\n}\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to index field 'text' (a nil value)\"\nactionForbiddenText = \"RXPGuides已被禁用，因为该功能只对暴雪的UI开放。\n你可以禁用这个插件并重新装载UI。\"\n",
["stack"] = "[Interface/AddOns/RXPGuides/Targeting.lua]:558: in function <Interface/AddOns/RXPGuides/Targeting.lua:557>\n[C]: ?\n[C]: in function 'Show'\n[Interface/AddOns/Blizzard_StaticPopup/StaticPopup.lua]:390: in function <...nterface/AddOns/Blizzard_StaticPopup/StaticPopup.lua:277>\n[C]: ?\n[C]: in function 'StaticPopup_Show'\n[Interface/AddOns/Decursive/Dcr_DIAG.lua]:877: in function '_ShowNotice'\n[Interface/AddOns/Decursive/DCR_init.lua]:1027: in function 'VersionWarnings'\n[Interface/AddOns/Decursive/DCR_init.lua]:1477: in function 'SetConfiguration'\n[Interface/AddOns/Decursive/DCR_init.lua]:1240: in function <Interface/AddOns/Decursive/DCR_init.lua:1155>\n[C]: ?\n[Interface/AddOns/BiSTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua]:66: in function <...AddOns/BiSTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>\n[Interface/AddOns/BiSTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua]:523: in function 'EnableAddon'\n[Interface/AddOns/BiSTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua]:626: in function <...AddOns/BiSTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>\n",
["session"] = 1747,
["counter"] = 4,
},
{
["message"] = "[ADDON_ACTION_FORBIDDEN] 插件 'RXPGuides' 尝试调用保护功能 'TargetUnit()'。",
["time"] = 1782839299,
["locals"] = "self = <table> {\n}\nevent = \"ADDON_ACTION_FORBIDDEN\"\naddonName = \"RXPGuides\"\naddonFunc = \"TargetUnit()\"\nname = \"RXPGuides\"\nbadAddons = <table> {\n RXPGuides = true\n}\nL = <table> {\n NO_DISPLAY_2 = \"|cffffff00标准的错误显示插件名叫 BugSack，可以在找到 !BugGrabber 的网站上找到它。|r\"\n ERROR_DETECTED = \"%s |cffffff00已抓取，点击链接获取更多信息。|r\"\n BUGGRABBER_STOPPED = \"|cffffff00用户界面有太多的错误。所以，游戏体验会被降低。如不想再看到此信息请禁用或升级失效插件。|r\"\n USAGE = \"|cffffff00用法：/buggrabber <1-%d>。|r\"\n STOP_NAG = \"|cffffff00!BugGrabber 将不再提示缺失错误显示插件信息知道下个版本发布。|r\"\n NO_DISPLAY_STOP = \"|cffffff00如果你不希望再次被提醒，请输入 /stopnag。|r\"\n NO_DISPLAY_1 = \"|cffffff00似乎没有与 !BugGrabber 一起运行的错误显示插件。虽然斜线命令访问错误报告，但错误显示插件可以以更快捷的方式帮助您管理这些错误。|r\"\n ERROR_UNABLE = \"|cffffff00!BugGrabber 本身无法检索其他玩家的错误。请安装 BugSack 或类似的错误显示插件，可能会包含这些功能。|r\"\n ADDON_CALL_PROTECTED = \"[%s] 插件 '%s' 尝试调用保护功能 '%s'。\"\n}\n",
["stack"] = "[Interface/AddOns/!BugGrabber/BugGrabber.lua]:554: in function '?'\n[Interface/AddOns/!BugGrabber/BugGrabber.lua]:538: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:538>\n[C]: ?\n[Interface/AddOns/RXPGuides/Targeting.lua]:502: in function <Interface/AddOns/RXPGuides/Targeting.lua:486>\n[C]: ?\n[C]: ?\n",
["session"] = 1747,
["counter"] = 1,
},
{
["message"] = "[ADDON_ACTION_BLOCKED] 插件 'WeakAuras' 尝试调用保护功能 'Frame:SetWidth()'。",
["time"] = 1782859782,
["locals"] = "self = <table> {\n}\nevent = \"ADDON_ACTION_BLOCKED\"\naddonName = \"WeakAuras\"\naddonFunc = \"Frame:SetWidth()\"\nname = \"WeakAuras\"\nbadAddons = <table> {\n WeakAuras = true\n}\nL = <table> {\n NO_DISPLAY_2 = \"|cffffff00标准的错误显示插件名叫 BugSack，可以在找到 !BugGrabber 的网站上找到它。|r\"\n ERROR_DETECTED = \"%s |cffffff00已抓取，点击链接获取更多信息。|r\"\n BUGGRABBER_STOPPED = \"|cffffff00用户界面有太多的错误。所以，游戏体验会被降低。如不想再看到此信息请禁用或升级失效插件。|r\"\n USAGE = \"|cffffff00用法：/buggrabber <1-%d>。|r\"\n STOP_NAG = \"|cffffff00!BugGrabber 将不再提示缺失错误显示插件信息知道下个版本发布。|r\"\n NO_DISPLAY_STOP = \"|cffffff00如果你不希望再次被提醒，请输入 /stopnag。|r\"\n NO_DISPLAY_1 = \"|cffffff00似乎没有与 !BugGrabber 一起运行的错误显示插件。虽然斜线命令访问错误报告，但错误显示插件可以以更快捷的方式帮助您管理这些错误。|r\"\n ERROR_UNABLE = \"|cffffff00!BugGrabber 本身无法检索其他玩家的错误。请安装 BugSack 或类似的错误显示插件，可能会包含这些功能。|r\"\n ADDON_CALL_PROTECTED = \"[%s] 插件 '%s' 尝试调用保护功能 '%s'。\"\n}\n",
["stack"] = "[Interface/AddOns/!BugGrabber/BugGrabber.lua]:554: in function '?'\n[Interface/AddOns/!BugGrabber/BugGrabber.lua]:538: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:538>\n[C]: in function 'SetWidth'\n[Interface/AddOns/WeakAuras/RegionTypes/Icon.lua]:332: in function 'UpdateSize'\n[Interface/AddOns/WeakAuras/RegionTypes/Icon.lua]:536: in function 'SetRegionWidth'\n[return function(newPositions, activeRegions)]:45: in function <[string \"return function(newPositions, activeRegions...\"]:1>\n[C]: in function 'xpcall'\n[Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua]:985: in function 'growFunc'\n[Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua]:1500: in function 'DoPositionChildren'\n[Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua]:1332: in function 'PositionChildren'\n[Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua]:1116: in function 'RunDelayedActions'\n[Interface/AddOns/WeakAuras/RegionTypes/DynamicGroup.lua]:1104: in function 'Resume'\n[Interface/AddOns/WeakAuras/WeakAuras.lua]:4991: in function <Interface/AddOns/WeakAuras/WeakAuras.lua:4944>\n[Interface/AddOns/WeakAuras/WeakAuras.lua]:5122: in function 'UpdatedTriggerState'\n[Interface/AddOns/WeakAuras/BuffTrigger2.lua]:2004: in function <Interface/AddOns/WeakAuras/BuffTrigger2.lua:1996>\n[Interface/AddOns/WeakAuras/BuffTrigger2.lua]:2498: in function <Interface/AddOns/WeakAuras/BuffTrigger2.lua:2491>\n",
["session"] = 1755,
["counter"] = 1,
},
{
["message"] = "[ADDON_ACTION_BLOCKED] 插件 'ElvUI' 尝试调用保护功能 'UNKNOWN()'。",
["time"] = 1782859785,
["locals"] = "self = <table> {\n}\nevent = \"ADDON_ACTION_BLOCKED\"\naddonName = \"ElvUI\"\naddonFunc = \"UNKNOWN()\"\nname = \"ElvUI\"\nbadAddons = <table> {\n WeakAuras = true\n ElvUI = true\n}\nL = <table> {\n NO_DISPLAY_2 = \"|cffffff00标准的错误显示插件名叫 BugSack，可以在找到 !BugGrabber 的网站上找到它。|r\"\n ERROR_DETECTED = \"%s |cffffff00已抓取，点击链接获取更多信息。|r\"\n BUGGRABBER_STOPPED = \"|cffffff00用户界面有太多的错误。所以，游戏体验会被降低。如不想再看到此信息请禁用或升级失效插件。|r\"\n USAGE = \"|cffffff00用法：/buggrabber <1-%d>。|r\"\n STOP_NAG = \"|cffffff00!BugGrabber 将不再提示缺失错误显示插件信息知道下个版本发布。|r\"\n NO_DISPLAY_STOP = \"|cffffff00如果你不希望再次被提醒，请输入 /stopnag。|r\"\n NO_DISPLAY_1 = \"|cffffff00似乎没有与 !BugGrabber 一起运行的错误显示插件。虽然斜线命令访问错误报告，但错误显示插件可以以更快捷的方式帮助您管理这些错误。|r\"\n ERROR_UNABLE = \"|cffffff00!BugGrabber 本身无法检索其他玩家的错误。请安装 BugSack 或类似的错误显示插件，可能会包含这些功能。|r\"\n ADDON_CALL_PROTECTED = \"[%s] 插件 '%s' 尝试调用保护功能 '%s'。\"\n}\n",
["stack"] = "[Interface/AddOns/!BugGrabber/BugGrabber.lua]:554: in function '?'\n[Interface/AddOns/!BugGrabber/BugGrabber.lua]:538: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:538>\n[C]: ?\n[C]: in function 'Show'\n[Interface/AddOns/Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameManager_Shared.lua]:501: in function 'CompactRaidFrameManager_UpdateContainerVisibility'\n[Interface/AddOns/Blizzard_CompactRaidFrames/Blizzard_CompactRaidFrameManager_Shared.lua]:143: in function 'CompactRaidFrameManager_UpdateShown'\n[Interface/AddOns/Blizzard_SettingsDefinitions_Frame/Classic/InterfaceOverrides.lua]:332: in function <...ingsDefinitions_Frame/Classic/InterfaceOverrides.lua:329>\n[C]: ?\n[Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua]:144: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143>\n[C]: ?\n[Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua]:147: in function 'TriggerEvent'\n[Interface/AddOns/Blizzard_SharedXMLBase/CvarUtil.lua]:118: in function <Interface/AddOns/Blizzard_SharedXMLBase/CvarUtil.lua:110>\n...[Interface/AddOns/GatherMate2/Display.lua]:574: in function 'UpdateMaps'\n[Interface/AddOns/GatherMate2/Display.lua]:326: in function '?'\n[Interface/AddOns/TalentEmuX/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua]:109: in function <...muX/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>\n[C]: ?\n[Interface/AddOns/TalentEmuX/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua]:19: in function <...muX/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>\n[Interface/AddOns/TalentEmuX/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua]:54: in function 'Fire'\n[Interface/AddOns/BiSTracker/Libs/AceEvent-3.0/AceEvent-3.0.lua]:120: in function <...AddOns/BiSTracker/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>\n[C]: in function 'ExpandSkillHeader'\n[Interface/AddOns/BiaoGe/Core/Module/RoleOverview.lua]:2029: in function <Interface/AddOns/BiaoGe/Core/Module/RoleOverview.lua:2026>\n[Interface/AddOns/BiaoGe/Core/Module/RoleOverview.lua]:2051: in function <Interface/AddOns/BiaoGe/Core/Module/RoleOverview.lua:2050>\n",
["session"] = 1755,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/!Pig/FramePlus/SkillFrame.lua:230: attempt to index field 'backdrop' (a nil value)",
["time"] = 1782862312,
["locals"] = "self = TradeSkillFrame {\n InvSlotDropdown = TradeSkillInvSlotDropdown {\n }\n selectedSkill = 0\n PixelSnapDisabled = true\n SubClassDropdown = TradeSkillSubClassDropdown {\n }\n ButList = <table> {\n }\n Frame = Frame {\n }\n ignoreFramePositionManager = true\n}\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"TOPLEFT\"\n(*temporary) = TradeSkillFrame {\n InvSlotDropdown = TradeSkillInvSlotDropdown {\n }\n selectedSkill = 0\n PixelSnapDisabled = true\n SubClassDropdown = TradeSkillSubClassDropdown {\n }\n ButList = <table> {\n }\n Frame = Frame {\n }\n ignoreFramePositionManager = true\n}\n(*temporary) = \"TOPLEFT\"\n(*temporary) = 530\n(*temporary) = -30\n(*temporary) = \"attempt to index field 'backdrop' (a nil value)\"\nSlotDropDown = TradeSkillInvSlotDropdown {\n menuPointX = 0\n menuMixin = <table> {\n }\n PixelSnapDisabled = true\n menuDescription = <table> {\n }\n Event = <table> {\n }\n __Center = Texture {\n }\n text = \"所有空格\"\n intrinsic = \"DropdownButton\"\n __BBorder = Texture {\n }\n hooked = true\n menuAnchor = <table> {\n }\n __TBorder = Texture {\n }\n callbackTables = <table> {\n }\n menuRelativePoint = \"BOTTOMLEFT\"\n __RBorder = Texture {\n }\n menuPointY = 0\n Arrow = Texture {\n }\n __LBorder = Texture {\n }\n Background = Texture {\n }\n Text = FontString {\n }\n menuPoint = \"TOPLEFT\"\n}\n",
["stack"] = "[Interface/AddOns/!Pig/FramePlus/SkillFrame.lua]:230: in function <Interface/AddOns/!Pig/FramePlus/SkillFrame.lua:226>\n[C]: ?\n[C]: ?\n[C]: ?\n[C]: in function 'Show'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager.lua]:592: in function 'SetUIPanel'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager.lua]:501: in function 'ShowUIPanel'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager.lua]:304: in function <...IParentPanelManager/Classic/UIParentPanelManager.lua:300>\n[C]: in function 'SetAttribute'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager.lua]:1082: in function 'ShowUIPanel'\n[Interface/AddOns/Blizzard_UIParent/Vanilla/UIParent.lua]:818: in function <...erface/AddOns/Blizzard_UIParent/Vanilla/UIParent.lua:358>\n[C]: ?\n[C]: in function 'CastSpell'\n[Interface/AddOns/Blizzard_UIPanels_Game/Vanilla/SpellBookFrame.lua]:188: in function 'OnIconClick'\n[Interface/AddOns/Blizzard_UIPanels_Game/Classic/SpellBookFrame.lua]:273: in function <...ns/Blizzard_UIPanels_Game/Classic/SpellBookFrame.lua:269>\n",
["session"] = 1755,
["counter"] = 1,
},
},
}
