local _, addonTable = ...

-- 当前 Classic Era 可用的宠物食物元数据，来源为 GFW_FeedOMatic 的 major = 1 数据。
addonTable.PetFeedFoodData = {
    [5525] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [5527] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [12216] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [4593] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [4603] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [21071] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [13889] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [4655] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [13929] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [13933] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [8364] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [27515] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [13546] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [787] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [8959] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [6290] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [21072] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [6308] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [1326] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [6316] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [2674] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [2675] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [6887] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [2682] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [27516] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [21552] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [13890] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [21153] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [13930] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [13934] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [21217] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [5468] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [5504] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [19996] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [12206] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [5095] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [13755] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [13759] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [4592] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [4594] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [16971] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [13927] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [13935] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [8957] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [6289] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [6291] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [6303] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [6317] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [13754] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [6361] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [12207] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [13756] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [13760] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [8365] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [15924] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [13893] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [13928] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [13932] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [13888] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [13758] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [7974] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [6889] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [6362] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [16766] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [5503] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Fish",
    },
    [5476] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [6038] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fish",
    },
    [12238] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fish",
    },
    [4371] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4387] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [10505] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [7191] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4404] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4357] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4389] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [15992] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4359] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4375] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [15994] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [18631] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4377] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [16000] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4364] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [814] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [16006] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4382] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [10558] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [10559] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [10560] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [10561] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Mechanical Bits",
    },
    [4606] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fungus",
    },
    [4607] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fungus",
    },
    [4604] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fungus",
    },
    [4608] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fungus",
    },
    [4605] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fungus",
    },
    [3448] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fungus",
    },
    [8948] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fungus",
    },
    [8953] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [13810] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fruit",
    },
    [21031] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [21033] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [20031] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [4536] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [4537] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [4538] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [4602] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [4539] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [11950] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fruit",
    },
    [19994] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [20516] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Fruit",
    },
    [21030] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [16168] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [22324] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Fruit",
    },
    [3666] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Bread",
    },
    [8950] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [2683] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Bread",
    },
    [8076] = {
        ["major"] = 1,
        ["category"] = "conjured",
        ["priority"] = 1,
        ["diet"] = "Bread",
    },
    [23160] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [17197] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Bread",
    },
    [4601] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [4540] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [4541] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [4542] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [19696] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [4544] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [13724] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [16169] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [19301] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Bread",
    },
    [1015] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [1017] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [12184] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [12208] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [19306] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [9681] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [4599] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [20424] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [21023] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [18045] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [17119] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [4739] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [12037] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [17407] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [3667] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [20074] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [3173] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [1081] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [2672] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [2673] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [12205] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [12209] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [12213] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [2679] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [2680] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [2681] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [2684] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [2685] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [3712] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [117] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [19995] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [3727] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [3728] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [3729] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [3730] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [3220] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [5470] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [5472] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [5474] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [5478] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [5480] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [3770] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [3771] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [8952] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [5051] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [7097] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [2287] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [12202] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [12210] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [21235] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [19223] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [11444] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [2886] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [2888] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [3404] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [729] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [2924] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [19224] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [2687] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [12203] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [17222] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [19304] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [6890] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [5479] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [1080] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [21024] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [12223] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [5465] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [5467] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [5469] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [5471] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [12204] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [5477] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [4457] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [19305] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Meat",
    },
    [3731] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [2677] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [769] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [723] = {
        ["major"] = 1,
        ["category"] = "inedible",
        ["priority"] = 4,
        ["diet"] = "Meat",
    },
    [13851] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [12224] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [3726] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [3662] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Meat",
    },
    [1707] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Cheese",
    },
    [17406] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Cheese",
    },
    [422] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Cheese",
    },
    [3927] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Cheese",
    },
    [8932] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Cheese",
    },
    [2070] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Cheese",
    },
    [12218] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Cheese",
    },
    [414] = {
        ["major"] = 1,
        ["category"] = "basic",
        ["priority"] = 2,
        ["diet"] = "Cheese",
    },
    [3665] = {
        ["major"] = 1,
        ["category"] = "wellfed",
        ["priority"] = 3,
        ["diet"] = "Cheese",
    },
}
